name: Hassfest

on:
  push:
    paths:
      - 'custom_components/**'
  pull_request:
    paths:
      - 'custom_components/**'

jobs:
  hassfest:
    name: Hassfest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: home-assistant/actions/hassfest@master
