input_number:
  house_inertia:
    name: House Inertia
    min: 0
    max: 5
    step: 0.01
    unit_of_measurement: "inertia points"

template:
  - trigger:
      - platform: time_pattern
        minutes: "/10"
      - platform: homeassistant
        event: start
    sensor:
      - name: "Indoor Temperature Delta"
        state: >
          {% set now = states('sensor.virtualoutdoortemp') | float %}
          {% set old = states('sensor.old_indoor_temp') %}
          {% if old is not none and old not in ['unknown', 'unavailable'] %}
            {{ (now - old | float) | round(2) }}
          {% else %}
            0
          {% endif %}
        unit_of_measurement: "°C"

      - name: "Old Indoor Temp"
        state: >
          {{ states('sensor.virtualoutdoortemp') }}
        unit_of_measurement: "°C"

  - sensor:
      - name: "Estimated House Inertia"
        state: >
          {% set previous = states('input_number.house_inertia') | float(0.1) %}
          {% set delta = states('sensor.indoor_temperature_delta') | float(0.1) %}
          {% set weighted = ((previous * 4) + delta) / 5 %}
          {{ weighted | round(2) }}
        unit_of_measurement: "inertia points"

automation:
  - alias: Update House Inertia
    trigger:
      - platform: time_pattern
        minutes: "0"
    action:
      - service: input_number.set_value
        target:
          entity_id: input_number.house_inertia
        data:
          value: "{{ states('sensor.estimated_house_inertia') }}"
