name: HACS Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly

jobs:
  hacs:
    name: HACS Validation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: HACS validation
      uses: hacs/action@main
      with:
        category: integration
        ignore: brands
