name: HACS Validation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Run HACS action
        uses: hacs/action@main
        with:
          category: integration  # 🟢 Detta är viktigt!
